### ISSUE TITLE
Doesn't seem to work with php 8.2.11 nor with php 7.4.33

### ISSUE THREAD

**Issue by anarkika** [Slevinski/SignPuddle2#1]
When I try to load the signpuddle (locally) I get these errors:

(php8)
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /opt/signpuddle/csw.php on line 204

(php7.4)
Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 204

Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 210

Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 212

Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 213

Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 215

Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 216

Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/signpuddle/csw.php on line 217

Fatal error: 'break' not in the 'loop' or 'switch' context in /opt/signpuddle/global.php on line 1247

**Comment by Slevinski** [comment]
SignPuddle 2 is currently running on the SignWriting Legacy server using PHP 5.4.

If you don't need SignText, you can try SignPuddle 3.
* Repo - https://github.com/Slevinski/apitxt
* Online - https://signpuddle.com/client/

**Comment by anarkika** [comment]
> SignPuddle 2 is currently running on the SignWriting Legacy server using PHP 5.4.

Thank you, but I found out that it works with php 5.6.40_9-2

(I was trying to revive a backup of an old private signpuddle... *groan*)

Hopefully, nobody's gonna ask me to make it work with php 8.

**Comment by Slevinski** [comment]
Good luck!
